# Generated by Django 5.1.6 on 2025-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_member',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('nhanvien', 'Nhân viên'), ('khachhang', 'Khách hàng')], default='khachhang', max_length=10),
        ),
    ]
