# Generated by Django 5.1.6 on 2025-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('SoDienThoai', models.CharField(max_length=12)),
            ],
        ),
    ]
