# Generated by Django 5.1.6 on 2025-03-07 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('MaPhongBan', models.AutoField(primary_key=True, serialize=False)),
                ('TenPhongBan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('SoDienThoai', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('MaPhongBan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.phongban')),
            ],
        ),
    ]
