# Generated by Django 5.1.6 on 2025-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('MaPhongBan', models.AutoField(primary_key=True, serialize=False)),
                ('TenPhongBan', models.CharField(max_length=100)),
            ],
        ),
    ]
