# Generated by Django 5.1.6 on 2025-03-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoPhanPhuTrach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.phongban')),
            ],
        ),
    ]
