# Generated by Django 5.1.6 on 2025-03-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phongban',
            name='TenPhongBan',
        ),
    ]
