# Generated by Django 5.1.6 on 2025-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_phongban_tenphongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='phongban',
            name='TenPhongBan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
