# Generated by Django 5.1.6 on 2025-03-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_phongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='MaPhongBan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.phongban'),
            preserve_default=False,
        ),
    ]
