# Generated by Django 5.1.6 on 2025-03-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
