# Generated by Django 5.1.6 on 2025-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='Task',
            field=models.IntegerField(default=0),
        ),
    ]
