# Generated by Django 5.1.6 on 2025-03-07 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('DiaChi', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThuePhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayThue', models.DateTimeField()),
                ('NgayNhan', models.DateTimeField()),
                ('NgayTra', models.DateTimeField()),
                ('TrangThai', models.CharField(choices=[('DA_DAT', 'Đã đặt'), ('DANG_O', 'Đang ở'), ('DA_TRA', 'Đã trả')], max_length=10)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.phong')),
            ],
        ),
    ]
