# Generated by Django 5.1.6 on 2025-03-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0004_alter_phong_trangthai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhachHang', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThuePhong',
            fields=[
                ('MaThue', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThue', models.DateTimeField()),
                ('NgayNhan', models.DateTimeField()),
                ('NgayTra', models.DateTimeField()),
                ('MaKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
                ('MaPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.phong')),
            ],
        ),
    ]
