# Generated by Django 5.1.6 on 2025-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_khachhang_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Diem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
