# Generated by Django 5.1.6 on 2025-03-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_khachhang_diem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuephong',
            name='NgayTra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
