# Generated by Django 5.1.6 on 2025-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_thuephong_ngaytra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuephong',
            name='TrangThai',
            field=models.CharField(choices=[('DA_DAT', 'Đã đặt'), ('DANG_O', 'Đang ở'), ('DA_TRA', 'Đã trả')], max_length=20),
        ),
    ]
