# Generated by Django 5.1.6 on 2025-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_thuephong_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='Diem',
        ),
    ]
