# Generated by Django 5.1.6 on 2025-03-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('MaDichVu', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Dịch Vụ')),
                ('TenDichVu', models.CharField(max_length=100, verbose_name='Tên Dịch Vụ')),
                ('GiaDichVu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá Dịch Vụ')),
            ],
        ),
        migrations.CreateModel(
            name='SuDungDichVu',
            fields=[
                ('MaSuDung', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Sử Dụng')),
                ('SoLuong', models.IntegerField(blank=True, null=True, verbose_name='Số Lượng')),
                ('NgaySuDung', models.DateField(blank=True, null=True, verbose_name='Ngày Sử Dụng')),
                ('MaDichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.dichvu', verbose_name='Mã Dịch Vụ')),
                ('MaThue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.thuephong', verbose_name='Mã Thuê')),
            ],
        ),
    ]
