# Generated by Django 5.1.6 on 2025-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('MaDichVu', models.AutoField(primary_key=True, serialize=False)),
                ('TenDichVu', models.CharField(max_length=100)),
                ('GiaDichVu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
