# Generated by Django 5.1.6 on 2025-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuDungDichVu',
            fields=[
                ('MaSuDung', models.AutoField(primary_key=True, serialize=False)),
                ('MaThue', models.IntegerField()),
                ('MaDichVu', models.IntegerField()),
                ('SoLuong', models.IntegerField()),
                ('NgaySuDung', models.DateField()),
            ],
        ),
    ]
