# Generated by Django 5.1.6 on 2025-03-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('service', '0002_sudungdichvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dichvu',
            name='GiaDichVu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá Dịch Vụ'),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='MaDichVu',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Dịch Vụ'),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='TenDichVu',
            field=models.CharField(max_length=100, verbose_name='Tên Dịch Vụ'),
        ),
        migrations.AlterField(
            model_name='sudungdichvu',
            name='MaDichVu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.dichvu', verbose_name='Mã Dịch Vụ'),
        ),
        migrations.AlterField(
            model_name='sudungdichvu',
            name='MaSuDung',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã Sử Dụng'),
        ),
        migrations.AlterField(
            model_name='sudungdichvu',
            name='MaThue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.thuephong', verbose_name='Mã Thuê'),
        ),
        migrations.AlterField(
            model_name='sudungdichvu',
            name='NgaySuDung',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày Sử Dụng'),
        ),
        migrations.AlterField(
            model_name='sudungdichvu',
            name='SoLuong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số Lượng'),
        ),
    ]
