# Generated by Django 5.1.6 on 2025-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_dichvu_phongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudungdichvu',
            name='TrangThai',
            field=models.CharField(choices=[('CHO_XU_LY', 'Chờ xử lý'), ('DANG_XU_LY', 'Đang xử lý'), ('HOAN_THANH', 'Hoàn thành')], default='CHO_XU_LY', max_length=20),
        ),
    ]
