# Generated by Django 5.1.6 on 2025-03-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_sudungdichvu_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudungdichvu',
            name='SoLuong',
        ),
    ]
