# Generated by Django 5.1.6 on 2025-03-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('MaLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoai', models.CharField(max_length=50)),
                ('GiaPhong', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('MaPhong', models.AutoField(primary_key=True, serialize=False)),
                ('soPhong', models.CharField(max_length=10)),
                ('TrangThai', models.CharField(choices=[('TRONG', 'Trống'), ('SU_DUNG', 'Đang sử dụng')], default='TRONG', max_length=20)),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.loaiphong')),
            ],
        ),
    ]
