# Generated by Django 5.1.6 on 2025-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phong',
            table='room_phong',
        ),
    ]
