# Generated by Django 5.1.6 on 2025-03-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='TrangThai',
            field=models.CharField(choices=[('TRONG', 'Trống'), ('SU_DUNG', 'Đang sử dụng')], default='TRONG', max_length=20),
        ),
    ]
