# Generated by Django 5.1.6 on 2025-03-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_phong_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phong',
            old_name='soPhong',
            new_name='SoPhong',
        ),
        migrations.AlterModelTable(
            name='phong',
            table=None,
        ),
    ]
