# Generated by Django 5.1.6 on 2025-03-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_sophong_phong_sophong_alter_phong_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='TrangThai',
            field=models.CharField(choices=[('TRONG', 'Trống'), ('SU_DUNG', 'Đang sử dụng'), ('DANG_DON_DEP', 'Đang dọn dẹp')], default='TRONG', max_length=20),
        ),
    ]
