# Generated by Django 5.1.6 on 2025-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHoaDon', models.AutoField(primary_key=True, serialize=False)),
                ('MaSDDV', models.IntegerField()),
                ('NgayLapHoaDon', models.DateField()),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
