# Generated by Django 5.1.6 on 2025-03-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('service', '0003_alter_dichvu_giadichvu_alter_dichvu_madichvu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='MaSDDV',
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaSuDung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.sudungdichvu', verbose_name='Mã Sử Dụng'),
        ),
    ]
