# Generated by Django 5.1.6 on 2025-03-12 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_thuephong_ngaytra'),
        ('invoices', '0002_alter_hoadon_masudung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='MaSuDung',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.thuephong'),
        ),
    ]
