# Generated by Django 5.1.6 on 2025-03-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_hoadon_masudung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoadon',
            old_name='MaSuDung',
            new_name='MaThue',
        ),
    ]
