# Generated by Django 5.1.6 on 2025-03-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_thuephong_ngaytra'),
        ('invoices', '0004_rename_masudung_hoadon_mathue'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='TrangThai',
            field=models.CharField(choices=[('DA_THANH_TOAN', 'Đã thanh toán'), ('CHUA_THANH_TOAN', 'Chưa thanh toán')], default='CHUA_THANH_TOAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='MaThue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.thuephong', verbose_name='Mã thuê'),
        ),
    ]
