# Generated by Django 5.1.6 on 2025-03-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_hoadon_trangthai_alter_hoadon_mathue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='TongTien',
        ),
    ]
